### PR TITLE
WIP: Add Follower Only Mode

### PR DESCRIPTION
**Pull request by jaredcat**
Currently untested and not complete in the current state.
Adds Follower Only mode to restrict songs to followers.
Requires a Twitch Client ID in order to get user IDs and check if a user is following another account.

### CODE REVIEW

**Comment by Wolfe-Coin** [comment]
could do donation only or donations only, after X in queue.

**Comment by jaredcat** [comment]
@Wolfe-Coin that would be a totally different integration with streamlabs or stream elements and outside the scope of this PR

**Comment by Soliel** [comment]
I'm working on getting the 0.12.0 update up, TI has ran into an infuriating issue unfortunately. After that gets done, let me know when this commit is fully tested and ready for merging. The AsyncTwitch Library is where PRs should go in order to add Twitch API calls and such. I wanna keep twitch completely abstracted out of BSR now.

**Comment by jaredcat** [comment]
Make sense, I'll try to get the code merged over there and then update this PR

**Pull request closed without merging**
